# Generated by Django 5.2.11 on 2026-02-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_rename_desc_club_description_club_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ecodrive',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
